#!/usr/bin/env python3
"""build-vocab.py — Controlled vocabulary extractor (IRF-RES-006, slice 1 of 3).

Harvests the *canonical* domain terms from the repo registry and emits a
machine-readable controlled-vocabulary registry at ``vocab.json``.

This is the FIRST SLICE of IRF-RES-006 (GH#339). Its single responsibility is
retroactive extraction of the names the system already uses. Two follow-up
slices are intentionally deferred and left as empty hooks here:

  * Slice 2 — synonymy reconciliation: populate each term's ``synonyms`` array
    (currently always ``[]``) by mining historical names, redirects, and aliases.
  * Slice 3 — CI validation hook: a pre-commit / Actions check that rejects new
    names in the registry that are not present in (or reconcilable to) vocab.json.

Three classes of canonical term are extracted from ``registry-v2.json``:

  1. organ        — organ identifiers (ORGAN-I … META-ORGANVM) + display names
  2. organization — GitHub org slugs (organvm-i-theoria, meta-organvm, …)
  3. repository   — canonical repo names

Plus the schema's CLOSED ENUMS, which are themselves controlled domain
vocabularies (status, tier, promotion_status, implementation_status, …). These
are tagged ``enum:<field>`` so that, e.g., the value ARCHIVED — which is a legal
value of both ``tier`` and ``promotion_status`` — is preserved as two distinct
terms rather than collapsed.

Usage:
    python3 scripts/build-vocab.py                       # writes ./vocab.json
    python3 scripts/build-vocab.py --registry registry-v2.json --output vocab.json
    python3 scripts/build-vocab.py --check               # exit 1 if vocab.json is stale

A dependency-free mirror of this extractor lives at ``scripts/build-vocab.jq``
for environments without Python (same extraction logic and output schema; the
committed vocab.json was generated by the jq mirror):
    jq -f scripts/build-vocab.jq repo-registry.json > vocab.json
"""

import argparse
import json
import sys
from pathlib import Path

# Closed-enum fields whose values are themselves controlled domain vocabulary.
# Each distinct value becomes a term under category "enum:<field>".
ENUM_FIELDS = [
    "status",
    "documentation_status",
    "promotion_status",
    "tier",
    "implementation_status",
    "ci_workflow",
    "functional_class",
    "type",            # ORGAN-III only (SaaS/B2B/B2C/internal)
    "revenue_model",   # ORGAN-III only
    "revenue_status",  # ORGAN-III only
]


def _add(terms: dict, category: str, value, source: str) -> None:
    """Register a canonical term under (category, value), recording its source.

    ``terms`` is keyed by the (category, value) pair so the same string in two
    different categories stays distinct. ``synonyms`` is seeded empty: filling
    it is slice 2's job.
    """
    if value is None or value == "":
        return
    value = str(value)
    key = (category, value)
    if key not in terms:
        terms[key] = {
            "term": value,
            "category": category,
            "synonyms": [],          # DEFERRED — populated in slice 2
            "sources": [],
        }
    if source not in terms[key]["sources"]:
        terms[key]["sources"].append(source)


def extract(registry: dict) -> list:
    """Walk the registry and collect every canonical term."""
    terms: dict = {}
    organs = registry.get("organs", {})

    for organ_id, organ in organs.items():
        _add(terms, "organ", organ_id, "organs.<id>")
        _add(terms, "organ_name", organ.get("name"), f"organs.{organ_id}.name")

        for repo in organ.get("repositories", []):
            _add(terms, "organization", repo.get("org"), "repositories[].org")
            _add(terms, "repository", repo.get("name"), "repositories[].name")
            for field in ENUM_FIELDS:
                if field in repo:
                    _add(terms, f"enum:{field}", repo[field],
                         f"repositories[].{field}")

    # Stable ordering: category, then term — deterministic output for clean diffs.
    return sorted(terms.values(), key=lambda t: (t["category"], t["term"]))


def build(registry_path: Path) -> dict:
    registry = json.loads(registry_path.read_text())
    terms = extract(registry)

    by_category: dict = {}
    for t in terms:
        by_category[t["category"]] = by_category.get(t["category"], 0) + 1

    return {
        "schema_version": "0.1.0",
        "irf": "IRF-RES-006",
        "slice": "1 of 3 — canonical name extraction",
        "generated_by": "scripts/build-vocab.py",
        "source": registry_path.name,
        "purpose": (
            "Controlled vocabulary registry for ORGANVM domain terms. Slice 1 "
            "extracts canonical names from the registry. Synonymy reconciliation "
            "(slice 2) and CI validation hook (slice 3) are deferred."
        ),
        "deferred": [
            "synonymy-reconciliation — populate each term synonyms[] (slice 2)",
            "ci-validation-hook — reject off-vocabulary names in CI (slice 3)",
        ],
        "term_count": len(terms),
        "category_counts": dict(sorted(by_category.items())),
        "terms": terms,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", default="registry-v2.json",
                        help="source registry (default: registry-v2.json)")
    parser.add_argument("--output", default="vocab.json",
                        help="output vocabulary file (default: vocab.json)")
    parser.add_argument("--check", action="store_true",
                        help="verify vocab.json is up to date; exit 1 if stale")
    args = parser.parse_args()

    registry_path = Path(args.registry)
    if not registry_path.exists():
        print(f"error: registry not found: {registry_path}", file=sys.stderr)
        return 2

    vocab = build(registry_path)
    rendered = json.dumps(vocab, indent=2, ensure_ascii=False) + "\n"

    output_path = Path(args.output)
    if args.check:
        current = output_path.read_text() if output_path.exists() else ""
        if current != rendered:
            print(f"stale: {output_path} does not match {registry_path}. "
                  f"Run: python3 scripts/build-vocab.py", file=sys.stderr)
            return 1
        print(f"ok: {output_path} is current ({vocab['term_count']} terms)")
        return 0

    output_path.write_text(rendered)
    print(f"wrote {output_path} — {vocab['term_count']} canonical terms across "
          f"{len(vocab['category_counts'])} categories")
    for cat, n in vocab["category_counts"].items():
        print(f"  {cat:28} {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
